### ISSUE TITLE
Pages that require authentication render VERY slowly

### ISSUE THREAD

**Issue by aviupadhyayula** [pennlabs/penn-clubs#594]
See title. I discovered this when trying to edit a club's application questions -- haven't validated it across other pages that require auth. My hunch is that renderPage.tsx is causing this. L164 implements a wrapper for any page that requires authentication, which queries the backend with an "is the current user == auth" upon any state change. Obviously, this is horrible when a user's inputting text. 

Proposed fix: query once upon auth-locked page load and don't do it again? 

[Example when updating a club application](https://github.com/pennlabs/penn-clubs/assets/69180850/caf31af7-10cd-4118-92f5-1e632d005b07)

**Comment by julianweng** [comment]
Tried to replicate but pages only reauthed upon submission, not sure if this was a result of frontend bumps (I only tested this with a local admin account: maybe there's a distinction since you are using a staff account?). Can you see if this still occurs for you?

https://github.com/pennlabs/penn-clubs/assets/10285518/2d54c59a-073d-40ca-bb3a-4e3f98c145d7

**Comment by aviupadhyayula** [comment]
Wasn't able to replicate this with a staff account either. Checks out that something in the frontend bumps fixed this. Thanks for following up!
